### ISSUE TITLE
Requesting config.ini example and graphite configuration

### ISSUE THREAD

**Issue by PifPof73** [jvehent/dmarc-parser#1]
Hi jvehent,
just saw your script by searching exactly this feature (dmarc parser in python).
I adjusted it to python3 and it is running and I get dmarc reports.
I still have some questions:
- could you please publish a example config.ini file? I am not sure what you are doing with this regex filtering 
- could you give some docu / hints what you have configured in graphite. I am newbe on this and just saw that your script sent data to the graphite server - but I do not know what to configure there to see something usefull.

If you want I can upload my adjustments to let the script run in python3.

Nice work, thanks a lot.
PifPof73

**Comment by jvehent** [comment]
I unfortunately do not have an example of config.ini. I wrote this code in 2012 and haven't touched it since (only backed it up 3 years ago).

**Comment by PifPof73** [comment]
No problem, I solved it myself through some reverse engineering and the good old try and error.
I forked a new version for python3 with example ini and some small adjustments.
